name: Auto Cancel Previous CI Runs
on:
  push:
    branches-ignore:
      - latest

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    if: "github.ref != 'refs/heads/latest'"
